### ISSUE TITLE
Add option to disable drivers

### ISSUE THREAD

**Issue by s1h4d0w** [d235j/360Controller#102]
Hi, 

I've recently bought Star Wars: The Force Unleashed and found out that my controller wasn't working, even though the game has explicit Xbox controller support. By Googling I found out that the game has its own drivers and that if you have a different (unofficial) driver it won't work.

So this means I will have to delete the files this driver uses to play SW:TFU, and then when I want to play a different game I will have to reinstall them and repeat the process when I want to play SW:TFU again.

It would be really handy to have a "disable driver" option in the OSX Preferences menu (along with an uninstall option).

Other than that the driver works beautifully, keep up the good work!

**Comment by Deph0** [comment]
This feature is already in the works.

**Comment by FranticRain** [comment]
There is a beta version of the driver that contains this feature. You can download it here: https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview6.pkg

**Comment by s1h4d0w** [comment]
Really awesome, thanks!

**Comment by mele113** [comment]
Thank You RodigroCard , It works perfectly version 0.15 and YosemiteOSX

**Comment by RodrigoCard** [comment]
I will close this and post the beta soon (for real), thanks!
