### ISSUE TITLE
How to uninstall the driver?

### ISSUE THREAD

**Issue by mishafeingold** [d235j/360Controller#104]
How do you remove the driver? I installed using the dmg package. I'm using Yosemite.

**Comment by RodrigoCard** [comment]
hello,

this latest preview build of the driver supports self-uninstallation AND can be disabled temporarily (maybe you need this for a specific game?)
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview6.pkg
(you may need to restart once)

a proper beta will be released soon

cheers!

**Comment by RodrigoCard** [comment]
duplicate of #98

**Comment by mishafeingold** [comment]
Thank you!
