### ISSUE TITLE
Disconecting the xbox controller from Mac

### ISSUE THREAD

**Issue by rrrvxi** [d235j/360Controller#106]
Hello, I installed the most recent version 0.15, it works with Yosemite 10.10.3, I have the official MS wireless for PC. All good, but does anybody knows if there a way to disconnect the controller without having to go to system preferences and then push the power off? I ask because in Windows I had a 3rd party program that just clicking on it automatically disconnected the control, in fact I remember I made a keyboard shortcut so it was even more efficient and FAST. If anyone know if this is possible on Mac please advise. Thanks

**Comment by RodrigoCard** [comment]
A Menu Bar for that and other functions would be great.
but for now, I suggest ou just pop out the batteries box, it is faster :)

**Comment by RodrigoCard** [comment]
This is duplicate of #47
