### ISSUE TITLE
GEM PAD EX Controller

### ISSUE THREAD

**Issue by elimo** [d235j/360Controller#114]
Can this controller please be added?

GEM PAD EX:

  Product ID:	0x550d
  Vendor ID:	0x24c6
  Version:	1.00
  Serial Number:	210021E0
  Speed:	Up to 12 Mb/sec
  Manufacturer:	HORI CO.,LTD
  Location ID:	0x14100000 / 1
  Current Available (mA):	500
  Current Required (mA):	Unknown (Device has not been configured)

**Comment by MaddTheSane** [comment]
Is it a 360 or Xbox One controller?

**Comment by elimo** [comment]
It's a 360 controller.

**Comment by RodrigoCard** [comment]
I will make a build with these and other changes.

**Comment by RodrigoCard** [comment]
Please install the latest version, https://github.com/d235j/360Controller/releases/tag/v0.15_beta2_unofficial Cheers!
