### ISSUE TITLE
Uninstall Xbox 360 Controler Drivers

### ISSUE THREAD

**Issue by asoksevil** [d235j/360Controller#117]
How can you uninstall it?

I have both the Xbox 360 and One controller and although the X360 is the wireless one with the USB cable, it doesn´t detect it so decided to go with the One that works flawlessly.

Thanks!

**Comment by FranticRain** [comment]
Just a note, unlike the Xbox One controller, plugging the play and charge kit into an Xbox 360 controller does not turn it into a wired controller. It is still a wireless controller and requires a wireless dongle to work. The beta version of this driver includes both Xbox One controller support and a built in uninstaller. You can check that out here: https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview6.pkg

**Comment by asoksevil** [comment]
Thanks for the fast reply.

As I already have "Xone Controller", which one do you recommend me to use it?

Also, I am trying to find the uninstaller but can´t find it...

**Comment by FranticRain** [comment]
Use this driver. It has more features than mine.

To uninstall "Xone-OSX" there is an uninstall.command included in the downloaded dmg. If you no longer have it, download the latest version and run the uninstaller from there. As for the 360Controller, simply install the new version over the old version. No uninstall required.

Once the new version is installed, the uninstall button for that driver is available in the bottom left hand corner of the advanced tab.

**Comment by asoksevil** [comment]
Got it thanks!

Works great for OpenEmu.

**Comment by jonathanhammond** [comment]
Hi i'm having issues with the builtin uninstaller on Install360Controller0.15Preview7 . Any advice?
<img width="1552" alt="screenshot 2015-07-17 17 02 36" src="https://cloud.githubusercontent.com/assets/1085712/8751474/29cdbe0a-2ca5-11e5-9b71-33f0230a6ff7.png">

**Comment by RodrigoCard** [comment]
@jonathanhammond disconnect your controller from your computer, restart, and then try again, it should work!

**Comment by asoksevil** [comment]
BTW, I have noticed that I am able to use the joy sticks on menus but I can´t use them outside of them while the D Pad works flawlessly on both cases.

I was able to replicate this issue using both Xone Controller and Xbox 360 Controler

**Comment by RodrigoCard** [comment]
there are issues in the uninstaller for latest Yosemite (10.10.4) And probably El Captain.
Fixed it in 64be136

please check the latest version
 https://github.com/d235j/360Controller/releases/tag/v0.15_beta_unofficial
