### ISSUE TITLE
Fifa 13 not supported.

### ISSUE THREAD

**Issue by ichu501** [d235j/360Controller#118]
First of all thanks to give the wonderful support.I need to use my 360 controller for FIFA 13 app, If i try to connect app will crash or the device not detected,Please give me a solution.

**Comment by MaddTheSane** [comment]
Sadly, there's not much we can do. If the game doesn't support game controllers at all, installing this driver won't make games automatically start working.

**Comment by RodrigoCard** [comment]
Yes. As @MaddTheSane said, There is nothing much we can do. This is probably a problem on the game itself.

Anyway, is it a windows version with a wrapper or something like that?

**Comment by RodrigoCard** [comment]
I will close this one, A quick search revealed this is a windows game unofficially ported.
So, a tip, in this screen:
![captura de tela 2015-07-28 as 01 42 41](https://cloud.githubusercontent.com/assets/417968/8923655/f5187b64-34c9-11e5-837e-ad8977335b86.png)
Google for "windows xbox controller mapping ids" or something like that and swap the button ids for the same as windows' button ids, I guess it should mostly work :)
