### ISSUE TITLE
Dankokp

### ISSUE THREAD

**Issue by dankokp** [d235j/360Controller#122]
Hi,
Thanks for driver, it works perfectly on Yosemite, except one thing. While gamepad is connecting, I have spinning leds around center "X" button. When it's connected, it works without any problems, but 4 green leds continue to flicker. It's a bit annoying, is there any way to fix it?

**Comment by RodrigoCard** [comment]
Is it wired or wireless controller?
anyway, please restart your mac once, just to be sure if the problem still happens

**Comment by dankokp** [comment]
I have wireless one. I downloaded the wrong version of driver. Right now I installed the right one and everything works perfect. I'm sorry for your time.
