### ISSUE TITLE
Can not re-enable driver after disabling

### ISSUE THREAD

**Issue by xythobuz** [d235j/360Controller#125]
Disabling the driver from the PrefPane works. However, after reenabling it, my controller is no longer detected. I need to reboot to get the driver to work again. Unplugging the (wired) controller does not help. It always shows "No devices found".

Using the 0.15 Beta.

**Edit:** The following also works instead of a reboot:

    sudo kextunload /Library/Extensions/360Controller.kext
    sudo kextload /Library/Extensions/360Controller.kext

**Comment by RodrigoCard** [comment]
This problem currently happens when you leave the prefpane with the driver disabled.

Try to disable/enable yet another time. That procedure doest exactly that commands you said.
