### ISSUE TITLE
[new device support] REAL ARCADE PRO. EX 

### ISSUE THREAD

**Issue by rickyngan** [d235j/360Controller#128]
REAL ARCADE PRO. EX:

  Product ID:	0xf504
  Vendor ID:	0x1bad

**Comment by RodrigoCard** [comment]
I will make a build with these and other changes.

**Comment by RodrigoCard** [comment]
Please install the latest version, https://github.com/d235j/360Controller/releases/tag/v0.15_beta2_unofficial Cheers!
