### ISSUE TITLE
Razer Sabertooth Elite

### ISSUE THREAD

**Issue by adamc92** [d235j/360Controller#20]
I can confirm that this method gives me a working controller (Razer Sabertooth Elite):
http://forums.macrumors.com/showthread.php?p=18789871#post18789871

However is it possible to get this controller working with this version so I don't have to deal with crashes??
The information for this controller is as follows:
  Product ID:	0xfe00
  Vendor ID:	0x1689
  Version:	 1.24
  Serial Number:	0773633A
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Razer
  Location ID:	0x14500000 / 10
  Current Available (mA):	500
  Current Required (mA):	500

Thanks, or if you could point me in the direction of how to help the project support it even better

**Comment by RodrigoCard** [comment]
I added that device in the list. Please test and tell us the results so we can close this issue:
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview3.pkg

Cheers!

**Comment by adamc92** [comment]
It works!
Thanks heaps for all your work I'm quite happy :+1:

**Comment by UpsetStarship** [comment]
Could you guys add support for the following Razer Sabertooth Elite controller?

Razer Sabertooth Elite:

  Product ID:	0x5d04
  Vendor ID:	0x24c6
  Version:	1.25
  Serial Number:	53BA15AF
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Razer
  Location ID:	0x04100000 / 4
  Current Available (mA):	500
  Current Required (mA):	Unknown (Device has not been configured)

**Comment by RodrigoCard** [comment]
Sure, I will do that soon.

**Comment by UpsetStarship** [comment]
Thank you!!

**Comment by RodrigoCard** [comment]
@UpsetStarship 
Hello, I just built a new pkg with some new devices included, please install, restart and test.
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview6.pkg

Cheers!

**Comment by mele113** [comment]
RodigroCard I installed 015from you link to dropbox and all went smooth and Yosemite 10.10,3 accepted it and it works perfectly with XBox 360 wired and wireelwss controllers. Thank you for all your excellent and dedicated work
