### ISSUE TITLE
Option to disable driver in PrefPane for use with OnLive.

### ISSUE THREAD

**Issue by jhaleit** [d235j/360Controller#21]
With the driver installed the xbox 360 controller doesn't work with OnLive. I would have to uninstall this driver for it to work. Would be great to have a button in PrefPane to be able to disable it so we don't have to uninstall and reinstall the driver if we want to use OnLive.

**Comment by MichalMMac** [comment]
:+1:  for this feature request
I am now playing Metal Gear Rising which supports x360 controller without driver. When driver is present, force feedback doesn't work. I can use kextunload but on/off toggle in prefPanel would be nice :)

**Comment by RodrigoCard** [comment]
included in eee7beb3be9b745d0e9e70cf6feec8dd967ab98c

**Comment by jhaleit** [comment]
Awesome! Thank you! Could we get a compiled package for this?

**Comment by RodrigoCard** [comment]
@jhaleit very soon.
