### ISSUE TITLE
Xbox One controller support

### ISSUE THREAD

**Issue by yummy527** [d235j/360Controller#28]
Dear developer, 
My friends and I have xbox one gamepad and sometimes want to use it on MAC.
Do you have a plan to develop a driver for xbox one controller for MAC OS X?

**Comment by FranticRain** [comment]
If you are interested in rolling my Xbox One controller driver into this one, let me know and I'll do what I can. Having all of the Microsoft controllers under one driver would be super convenient.

**Comment by MaddTheSane** [comment]
I do agree with the statement that having the drivers together would be appreciated.

I have no issue with this. @d235j, @RodrigoCard: thoughts?

**Comment by RodrigoCard** [comment]
So, after messing with some expired signature certificates (phew), I built the latest commit, get it here
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview1.pkg

I tested both wireless 360 controllers and a xbox one controller, both worked correctly (I dont have a xbox original controller, though)
![captura de tela 2015-01-16 as 00 37 25](https://cloud.githubusercontent.com/assets/417968/5770866/ca9b6f06-9d19-11e4-9f7f-af7f945ae85c.png)

Does the rumble works for XOne controllers in the prefpane (cant test in a game right now) ? It doesnt work for me.

Also, I am not sure if there is something broken, or if I did something wrong, but *the Prefpane is not working at all*.

**Comment by FranticRain** [comment]
The Prefpane doesn't work for me either, but the rumble still works for the Xbox One controller in Fez.

**Comment by MaddTheSane** [comment]
What, exactly, is wrong with the PrefPane?
Also, what version of OS X are you using?

**Comment by FranticRain** [comment]
OS X 10.10.1

As for what happens with the PrefPane, it doesn't load at all.
![Blank Preference Pane](http://imgur.com/PbYz1hx)

**Comment by MaddTheSane** [comment]
Does anything show up in the Console app?

**Comment by FranticRain** [comment]
I'm unsure as to what you mean by the console app, but testhaptic does work.

**Comment by MaddTheSane** [comment]
The Console app is the application located at `/Applications/Utilities/Console.app` that shows what various apps have put into the console. Look for anything that says `System Preferences`: it'll help.

**Comment by FranticRain** [comment]
Oh duh. Sorry. I'm such a Windows guy that I just think Console/Command Prompt/Terminal are all the same thing. Unfortunately, the console isn't terribly useful either.

1/15/15 9:58:08.362 PM System Preferences[6470]: [NSPreferencePane loadMainView]: Could not load nib at "(null)"
1/15/15 9:58:08.392 PM System Preferences[6470]: No settings found

**Comment by FranticRain** [comment]
Also a weird side note. It looks like the Xbox One controller works with Aspyr titles (Ex. Borderlands 2) with the driver installed. No such luck with OnLive though. Don't know if that fix was intentional or not.

**Comment by MaddTheSane** [comment]
To my knowledge, OnLive wants direct access to the 360 controller on OS X. Any driver would prevent this.
I don't know if it supports The Xbox One controller, though.

**Comment by RodrigoCard** [comment]
@MaddTheSane The last commit 38b4a391d9376ef9ec5e9ce4ef475276aa018480 seems to have fixed the pref pane issue. So here we go:
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview2.pkg

the prefpane worked pretty well for me, including the trigger-rumble tests.

**Comment by FranticRain** [comment]
Works well for me too. Note that the rumbles are the controller's rumbles and not the Xbox One's included impulse triggers. I can wire those up if you want, but seeing as no games support these triggers, it seems like a waste of time.

**Comment by MaddTheSane** [comment]
I'd say add them: games may support them in the future.

**Comment by RodrigoCard** [comment]
@FranticRain Oh please do. If it is easy.

Would be interesting to include an option to redirect the "regular" rumble functionality to the triggers if the user wants. Not sure if that would work well.

**Comment by FranticRain** [comment]
Its all the same packet really. I just need to use @MaddTheSane 's multiple classes for the ForceFeedback stuff and report that the controller supports FFJOFS_Z. I'm not sure at the moment how games would implement it, seeing as there are two triggers and one axis. As for switching the regular rumble to impulse trigger, its literally just moving the rumbles down two bytes in the packet to do that.

**Comment by yummy527** [comment]
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview2.pkg
this one could not be installed.

**Comment by RodrigoCard** [comment]
@yummy527 are you sure? it is working for me and other people. Could you try again?

@FranticRain If you enable the rumble triggers for multiple classes of ForceFeedback stuff, how do we use that? Just to understand.
If it can "just work", could you please enable them?

Btw, I will close this since the main subject is done anyway! :)

Thanks everybody

**Comment by FranticRain** [comment]
I'm working on an update to the Pref Pane that adds a Popup box that lets the user choose between normal rumble, triggers, and both. As for making that trigger rumble available to developers, @MaddTheSane has a MultipleFFDrivers branch that I would need to mess with a bit to make work.

**Comment by RodrigoCard** [comment]
Oh. Great! :)

**Comment by yummy527** [comment]
I am sure that 0.15preview2 can not be installed on my imac, but 0.15preview1 is OK. It works well except the pref in System setting show nothing.

![2015-02-01_23-39-27](https://cloud.githubusercontent.com/assets/9738778/5992620/eeab60ae-aa6b-11e4-9fcf-e1ecd22973a5.png)

**Comment by RodrigoCard** [comment]
@yummy527  The installer aparently have a problem updating the prefpane in new installations.
the newly installed prefpane simply dont work sometimes.

Please try this:
* Remove the Xbox Preference pane form the System preferences (right-click on its icon)
* Remove any kind of xbox devices from all off your usb ports.
* Restart your mac
* Install the pkg again
* now plug the controller(s)

**Comment by RodrigoCard** [comment]
@yummy527 anyway, try this one https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview3.pkg

**Comment by yummy527** [comment]
Hi, RodrigoCard.
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview3.pkg  This one could not be installed,either

![2015-02-07_10-34-51](https://cloud.githubusercontent.com/assets/9738778/6090474/e935e650-aeb5-11e4-9051-cbec42b5e8b2.png)

**Comment by yummy527** [comment]
Hi, RodrigoCard.
I redownloaded  preview3. OK now! 
Thanks.
