### ISSUE TITLE
Horipad EX2 Turbo refuses to work with 360Controller

### ISSUE THREAD

**Issue by blahblah666** [d235j/360Controller#38]
I'm running OS X 10.10.1 on a mid-2012 MBP and a late 2009 Mac Mini. 360Controller doesn't work with my EX2 Turbo, on the MPB or the Mini. It doesn't show up as a device under the XBox 360 Controllers preference. No game or emulator can see it. 

It does show up under System Report->USB and works perfectly in Windows 7 running under Parallels, though. 

I even tried deleting 360Controller from the MBP and using Tattieboggle's driver + workarounds. Still nothing. What's going on?

**Comment by RodrigoCard** [comment]
Could you test your controller with this version?
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview2.pkg

Please restart once, if you have used the driver since the last time you boot your computer.

**Comment by RodrigoCard** [comment]
This device was already in the Info.plist
```
HoriUnnamed,7085,21760
```
And there is another device with "HoriPad EX2 turbo" name in the plist
```
HoriPadEX2Turbo,7085,62721
```

anyway, it should be working, if you can, please test.
