### ISSUE TITLE
[BETOP (GAME FOR WINDOWS)] (not supported device)

### ISSUE THREAD

**Issue by tdlrobin** [d235j/360Controller#41]
[BETOP (GAME FOR WINDOWS)]：

  产品 ID：	0x5506
  厂商 ID：	0x11c0  (Sanmos Microelectronics Corp.)
  版本：	1.00
  速度：	最大 12 Mb/秒
  制造商：	HJC Game
  位置 ID：	0x14200000 / 3
  可用电流 (mA)：	500
  所需电流 (mA)：	500

**Comment by RodrigoCard** [comment]
I added that device in the list. Please test and tell us the results so we can close this issue:
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview3.pkg

Cheers!

**Comment by RodrigoCard** [comment]
@tdlrobin did you see the update?

**Comment by RodrigoCard** [comment]
Does anyone have athis controller to help use testing this?
The latest preview build can be downloaded here:
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview4.pkg

if there is no feedback or if someone tell us that succeeded in using this game controller with this driver, I will close this issue soon to clean the issue list for the next release.

Cheers!
