### ISSUE TITLE
MadCatz FightPad (New device)

### ISSUE THREAD

**Issue by guillaume-aleph** [d235j/360Controller#43]
Hi,

Could you add the support for this pad?
Thanks!

Mad Catz FightPad:

Product ID: 0xf02e
Vendor ID: 0x1bad
Version: 4.90
Serial Number: 1871A46A
Speed: Up to 12 Mb/sec
Manufacturer: Mad Catz, Inc.
Location ID: 0xfd140000 / 5
Current Available (mA): 500
Current Required (mA): Unknown (Device has not been configured)

**Comment by RodrigoCard** [comment]
I added that device in the list. Please test and tell us the results so we can close this issue:
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview3.pkg

Cheers!

**Comment by guillaume-aleph** [comment]
Oops, 404 error. I can't download the file. I'll try later.

**Comment by RodrigoCard** [comment]
The link should be working now, please try again.

**Comment by guillaume-aleph** [comment]
Yeah! My pad is working too! You're great!

Thank you!
