### ISSUE TITLE
Can't find the software anywhere on Mac

### ISSUE THREAD

**Issue by AntRln** [d235j/360Controller#52]
Hey,

I think I'm dumb as hell but I've tried to install this sofware maybe 15 times and everytime it has finished installing it, I can't find the software anywhere : nor in my Files or my Apps ... Someone please help me !! 

I'm using a MacBook Pro with OSX Yosemite 10.10

**Comment by slime73** [comment]
It should appear as a pane in the System Preferences app, at the bottom.

**Comment by AntRln** [comment]
Thanks man, I just figured it out ... God I'm so stupid --"

**Comment by MaddTheSane** [comment]
I am thinking of adding a menu item if there is a wireless controller connected.
