### ISSUE TITLE
Screensaver turns on while playing

### ISSUE THREAD

**Issue by AndreasBoehm** [d235j/360Controller#57]
Yesterday i tried to play "Broforce" with my brand new XBOX 360 Wireless Controller with your driver under OSX 10.10.1. It worked well, but the screensaver appeared while playing.

Is this game-related or input-device related?
I think it could be a combination of both, havent tried any other game.

**Comment by maybeageek** [comment]
I think it might be input device related, it happened here too with Sonic All Stars Racing.

**Comment by slime73** [comment]
That'd be up to the game's code. Typically a game will have a repeating timer that stops the screensaver from activating every few seconds, while the game is in the foreground. Games that use SDL can just call the handy `SDL_DisableScreenSaver` function. Recent versions of SDL even do that by default.

**Comment by RodrigoCard** [comment]
Does it happen with other games?

**Comment by khallmark** [comment]
This is an issue with controllers in general, I think. I had issues with it in every game I was playing with a dualshock4 also.

**Comment by MaddTheSane** [comment]
This is less an issue with controllers and more an issue with games *not* telling the OS not to turn on the screen saver. Although this may be because older games are using outdated APIs which may not work on newer OSes.

**Comment by khallmark** [comment]
I've noticed the same behavior running in Parallels.

Connect the controller to Mac, share the usb device to Parallels (in this case a DualShock 4), play games. Screen shuts off according to energy saver. It could also be an issue with Parallels too. 

It's definitely a common issue with gaming pads, whether it's each application or the system itself.

**Comment by RodrigoCard** [comment]
unfortunately , as @MaddTheSane said, this is something that the games themselves should worry about. So, not a bug.
