### ISSUE TITLE
List of compatible controllers 

### ISSUE THREAD

**Issue by Duros** [d235j/360Controller#63]
I can't seem the find a list of compatible controllers with this driver.
Maybe it's a idea to include this in the [Readme](https://github.com/d235j/360Controller/blob/master/Readme.md) of the driver?

**Comment by Pyroh** [comment]
In this [file](https://github.com/d235j/360Controller/blob/master/360Controller/Info.plist) contains the list of compatible controllers.
Feel free to make a new wiki page with these informations.

**Comment by Duros** [comment]
Thanks. I'll try, correct me if I am wrong.

**Comment by Duros** [comment]
Oke, I am pretty new to this. It seems like I am not able to create a custom side, I can only add that in the wiki of my own fork. Do I have to make a push request for that?

**Comment by RodrigoCard** [comment]
Yes, you Can NOT pull changes on github wikis, which is a shame
http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

you need to edit the wiki of the main repository. Do you have access?

**Comment by Duros** [comment]
I can't because the option is not simply there. I think only collaborators can do this, or something is checked in the setting why I can't do it. [This](http://imgur.com/N5rdYdV) is all I can see.

**Comment by RodrigoCard** [comment]
I created the pages and the custom sidebar, could you check if you can edit them?

**Comment by Duros** [comment]
Yes I can edit the custom sidebar, thanks.

**Comment by RodrigoCard** [comment]
Nice. closing.

If you need another page, tell me here and I will create it.
Feel free to edit/add/fix any info.
