### ISSUE TITLE
Duration of active force feedback effects is affected when the user's system clock changes

### ISSUE THREAD

**Issue by slime73** [d235j/360Controller#70]
If the system clock is changed via System Preferences (or if it gets changed automatically by OS X), active Force Feedback effects are affected – e.g. if an effect that lasts 10 seconds is started at 2:05:00 and then the system clock is changed to 2:04:00, it will last 1 minute and 10 seconds instead of 10 seconds.

This is because the Feedback360 and Feedback360Effect code uses the `CFAbsoluteTimeGetCurrent` function, which is based on the system clock rather than a monotonically increasing one:

> Repeated calls to this function do not guarantee monotonically increasing results. The system time may decrease due to synchronization with external time references or due to an explicit user change of the clock.

I think the code should use `mach_absolute_time` plus whatever is available to convert its units into nano/micro/seconds (or some other monotonic time function), instead of `CFAbsoluteTimeGetCurrent`.

**Comment by MaddTheSane** [comment]
Nice catch. I'll look into it.
