### ISSUE TITLE
Add new controller

### ISSUE THREAD

**Issue by rubiesonthesky** [d235j/360Controller#74]
I'd like to kindly ask you could add this controller to your list. It is nameless but it was popular (and blue) on ebay where I bought it. 

Controller
  Product ID:	0xf301
  Vendor ID:	0x046d  (Logitech Inc.)
  Version:	1.10
  Serial Number:	102CE9F
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Microsoft Inc.
  Location ID:	0x14240000 / 15
  Current Available (mA):	500
  Current Required (mA):	Unknown (Device has not been configured)

![](http://puu.sh/fDJhv/9a17a4febb.png)

**Comment by RodrigoCard** [comment]
I added your device, please test it: ;)
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview4.pkg

Cheers!

**Comment by rubiesonthesky** [comment]
It works so nice now! Thank you!

**Comment by GoshDamn** [comment]
you are my hero and i love you

**Comment by RodrigoCard** [comment]
@GoshDamn You should love everyone that contributed to this project, really :)
