### ISSUE TITLE
Add new Device: Speedlink Strike FX Wireless

### ISSUE THREAD

**Issue by leukhin** [d235j/360Controller#78]
Hello, 
Is it any chance Speedlink Strike FX Wireless to be added?
I have tried to add it by myself to Info.plist, but no luck.

The issue is this is wireless controller with radio receiver. And it is visible on USB section on mac, but when I power on controller it cannot establish connection to receiver. I don't know is this request applicable to 360Controller. If not - just close this issue. 

I'm googled a lot for solution and I didn't found any approach.

This is how controller looks:
![strike_fx_wireless_gamepad_controller_voor_ps3_en_pc_front](https://cloud.githubusercontent.com/assets/863778/6210408/259049b4-b5d8-11e4-8cea-e423064d8812.jpg)

This is my USB info: 
![screen shot 2015-02-16 at 12 35 42](https://cloud.githubusercontent.com/assets/863778/6210428/5c642820-b5d8-11e4-8b51-d8b75bfc9944.png)

Thanks a lot!

**Comment by RodrigoCard** [comment]
Hello,
This driver was made for Xbox and Xinput devices in mind, not regular HID controllers.
Sorry

**Comment by leukhin** [comment]
@RodrigoCard Yes, no problem.

Thanks.
