### ISSUE TITLE
Thrustmaster GPX Gamepad

### ISSUE THREAD

**Issue by FactSphere** [d235j/360Controller#88]
Would you be so kind to add the following device?

GPX Gamepad:

  Product ID:	0xb326
  Vendor ID:	0x044f  (ThrustMaster, Inc.)
  Version:	4.02
  Serial Number:	00000001
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Thrustmaster
  Location ID:	0xfa130000 / 5
  Current Available (mA):	500
  Current Required (mA):	Unknown (Device has not been configured)

Thanks!

**Comment by RodrigoCard** [comment]
sure, I will add that soon.

**Comment by RodrigoCard** [comment]
Hello, I just built a new pkg with some new devices included, please install, restart and test.
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview6.pkg

Cheers!

**Comment by FactSphere** [comment]
It works perfectly, finally I can play "I am Bread" on OS X :D Thank you!
