### ISSUE TITLE
Pro Ex mini Blue

### ISSUE THREAD

**Issue by Peanut90** [d235j/360Controller#89]
Would it be possible to add this controller?

Pro Ex Mini Blue

Product ID:	0x531a
  Vendor ID:	0x24c6
  Version:	1.00
  Serial Number:	0002F1C1
  Speed:	Up to 12 Mb/sec
  Manufacturer:	BDA
  Location ID:	0xfa130000 / 6
  Current Available (mA):	500
  Current Required (mA):	Unknown (Device has not been configured)

Thank you!

**Comment by RodrigoCard** [comment]
The device was already on the list of current Development version with the name "Pro Ex Mini Green 2", apparently, the ids are the same no matter the colors.
please test this preview version:
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview5.pkg
install, restart, and tell me if that works.

Cheers!
