### ISSUE TITLE
Xbox 360 racing wheel

### ISSUE THREAD

**Issue by codecowboy** [d235j/360Controller#90]
Has anyone tested this with the Xbox racing wheel + pedals?

**Comment by RodrigoCard** [comment]
No. Do you have one? If it is not working, maybe it is just a matter of adding its vendor/product ids to the info.plist.

**Comment by codecowboy** [comment]
I do but its wireless so would need to buy the receiver to see if it works
and not sure if its worth it if the driver won't work. Its this one:

http://en.m.wikipedia.org/wiki/Xbox_360_Wireless_Racing_Wheel

**Comment by RodrigoCard** [comment]
we will be glad to add this device IDs once somebody can send it to us and test,
we just cant guarantee it will work properly before that.

If you (or someone else) get the Receiver and the controller together, please reopen this issue and include the device IDs.

Thank you!

**Comment by MrSnowflake** [comment]
How can I get the device id of the wireless wheel? I have the original Xbox 360 Wireless wheel.

**Comment by deansallinen** [comment]
I also have the Xbox 360 Racing wheel + Pedals and would like to see support included! How do I find the device ID?
