### ISSUE TITLE
Help with deactivating vibrations

### ISSUE THREAD

**Issue by BCMNG** [d235j/360Controller#92]
Hey there,
I was searching for updated versions and was lucky enough to land here.

I use a wired XB360 controller and play almost only CS:GO (I know, I know... :) ).

Apart from some hickups with the movement with the analog sticks, the only thing really giving me a hard time are the vibrations. I tried it with re-mapping and using different buttons for shooting - still - just doesn't feel right. So I was hoping that someone here can maybe help me out.

I have 0 experience with commands/terminal. Is there a way to deactivate the vibrations without taking the controller apart and without messing up my mac.

Don't want to sound stupid. I really don't have any clue how to change it.

And thank you all for keeping this alive!

**Comment by MaddTheSane** [comment]
The game itself should have a way of disabling force feedback, either in game or controller settings.

**Comment by BCMNG** [comment]
There isn't. I made screenshots from everything
* Steam
* Steam Big Picture
* Counter Strike: Global Offensive (in game)

I can't find it. Maybe I'm looking at the wrong place?
Google/Steam forums - no luck either.

Here are the pictures - http://imgur.com/a/a7zRs
Let me know if the link doesn't work.

**Comment by BCMNG** [comment]
Can be closed. Opened the controller and took the rumble packs out.

**Comment by Deph0** [comment]
Maybe we could implement this next to the disable driver options in #82 ?

**Comment by Contez** [comment]
I agree with Deph0.
It could be useful.

**Comment by RodrigoCard** [comment]
@Contez @Deph0 @BCMNG 
This option will be added soon, Thanks to @FranticRain .
See #94 
Closing this one.
